### ISSUE TITLE
indentation will disappear after clicking 'show the code'

### ISSUE THREAD

**Issue by zhuxiaochu** [Teteruga/textindent#5]
before clicking, it is as follows,
`<p style="text-indent: 2em;">test</p>
`
after clicking 'show the code' button,it changes to
`<p>test</p>
`
It looks like inline style will be filtered,I guess it's designed for safety.

**Comment by Teteruga** [comment]
Ckeditor has a [filter](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_acf.html) that removes every tags and styles if they are not allowed by default. This plugin enables the `text-indent` style on `<p>` tags so you shouldn't have problems with it unless you change what is allowed and what isn't.
I just downloaded Ckeditor with the plugins and it didn't remove the style so take a loot at your code and see if you are changing the filter.

**Comment by zhuxiaochu** [comment]
good! [filter](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_acf.html) helps me.But there is still a little problem, I need add `extraAllowedContent: 'p{text-indent}'` in config by myself. it looks like this plugin doesn't enable the `text-indent` style on `<p>` tags.And i have never changed filter before.

**Comment by Teteruga** [comment]
So as i just told you i downloaded Ckeditor version 4.11 standart preset plus the plugin and tested, it all went well, so i will need you to give me some info about your download/instalation so i can help you.

**Comment by zhuxiaochu** [comment]
Thks! you can check the ckeditor that i used at [my repository](https://github.com/zhuxiaochu/microblog/tree/prod/app/static/ckeditor).Though I use a python library to call ckeditor in the project,you needn't consider it.Because when i used `CKEDITOR.replace` directly,it already happened this problem.
In addition:
`<script >
    CKEDITOR.replace('editor1', {
        indentation: '10px',
    })
</script>`
`10px` only works when enclosed by quotes.

**Comment by Teteruga** [comment]
Okay thanks for the correction about the quotes i'll change it in the README.
So about the  error i still can't find what is wrong so i'll try one last thing.
Create a simple page with ckeditor something like this(or similar for your setup)):

```
<!DOCTYPE HTML>
<html>
	<head>
	<meta charset="utf-8">
        <title>A Simple Page with CKEditor</title>
        <script type="text/javascript" src="./ckeditor_standart_textindent/ckeditor/ckeditor.js"></script>
	</head>
<div class = 'ckeditor'>
<textarea name="editor1" id="editor1" rows="10" cols="80">
            This is my textarea to be replaced with CKEditor.
 </textarea>
</div>
<script>
var editor = CKEDITOR.replace( 'editor1', {
	extraPlugins: "textindent",
});
editor.on( 'instanceReady', function() {
    console.log( editor.filter.allowedContent );
} );
</script>
```

the important part is to get the Ckeditor instance, in this case the editor var and setup this hook.

`editor.on( 'instanceReady', function() {
    console.log( editor.filter.allowedContent );
} );`

see if you can find anything like this :
` {elements: {…}, classes: null, styles: {…}, attributes: null, featureName: "ident-paragraph", …}` 
in your console.

If you can't find this in the console it means that the plugin didn't change the filter therefore it will remove the style and i wouldn't know how because the plugin is working and i've done a lot of test these days.

If you find it then i'll be kinda of lost so more info would help me find why.
